### ISSUE TITLE
Filter buttons do not work on Firefox

### ISSUE THREAD

**Issue by ethman** [csteinmetz1/AutomaticMixingPapers#6]
Thanks for making such a cool resource!

The filter buttons on the main page (e.g., "Level", "Reverb", etc) do not work on Firefox. I'm using Firefox 75.0 on macOS Mojave (10.14.6). Works fine on a chromium browser on the same machine. The error I see in the console is:

`TypeError: $(...).DataTable is not a function`

**Comment by csteinmetz1** [comment]
Hey, thanks for checking it out!

Sorry to hear you had this issue. I tried to reproduce it (Firefox 75.0 and Mojave 10.14.16 as well), but the filter buttons appear to be working for me. I am curious if there is another extension or setting within the browser that may be blocking the import of the DataTable library in your case. I will update this issue if I find anything.

Thanks for bringing this to my attention.

**Comment by ethman** [comment]
Oh, hmmm. I do have an anti-tracking extension and it looks like Privacy Badger is flagging the DataTables CDN. Looking at the Privacy Badger docs, this seems like they intentionally cast a wide net with regards to third party libraries (though I don't usually have an issue). I've filed a bug report with them.

Sorry for the false alarm, and cool site!!!
